version: "3.3"

services:
  mariadb:
    image: mariadb
    container_name: strawberry
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8085
